# ############################################################################
# Model: E2E ASR with attention-based ASR
# Encoder: CRDNN model
# Decoder: GRU + beamsearch + RNNLM
# Tokens: BPE with unigram
# losses: CTC+ NLL
# Training: Librispeech 960h
# Authors:  Ju-Chieh Chou, Mirco Ravanelli, Abdel Heba, Peter Plantinga 2020
# ############################################################################

# Seed needs to be set at top of yaml, before objects with parameters are made
seed: 7
__set_seed: !!python/object/apply:torch.manual_seed [!ref <seed>]
output_folder: !ref results/CRDNN_BPE_RNNT_LM_100H/<seed>
wer_file: !ref <output_folder>/wer.txt
save_folder: !ref <output_folder>/save
train_log: !ref <output_folder>/train_log.txt
lm_ckpt_file: https://www.dropbox.com/s/6uy5m6jaf0t769i/model.ckpt?dl=1

# Tokenizer model
tok_mdl_file: https://www.dropbox.com/s/o7gnouwdoqchotj/1000_unigram.model?dl=1
tok_voc_file: https://www.dropbox.com/s/7l8z622cpd3t8st/1000_unigram.vocab?dl=1

# Data files
data_folder: !PLACEHOLDER
# If RIRS_NOISES dir exists in /localscratch/xxx_corpus/RIRS_NOISES
# then data_folder_rirs should be /localscratch/xxx_corpus
# otherwise the dataset will automatically be downloaded
data_folder_rirs: !PLACEHOLDER
#train_splits: ["train-clean-100", "train-clean-360", "train-other-500"]
train_splits: ["train-clean-100"]
dev_split: dev-clean
csv_train: !ref <data_folder>/train.csv
csv_valid: !ref <data_folder>/<dev_split>.csv
csv_test_clean: !ref <data_folder>/test-clean.csv
csv_test_other: !ref <data_folder>/test-other.csv


# Training parameters
number_of_epochs: 30
number_of_ctc_epochs: 20
number_of_ce_epochs: 20
batch_size: 8
batch_size_valid: 4
lr: 1.0
ctc_weight: 0.33
ce_weight: 0.33
device: 'cuda'
ddp_procs: 0  # Set to number of GPUs for multi-gpu training
token_type: unigram  # ["unigram", "bpe", "char"]

# Feature parameters
sample_rate: 16000
n_fft: 400
n_mels: 40

# Model parameters
activation: !name:torch.nn.LeakyReLU
dropout: 0.15
cnn_blocks: 2
cnn_channels: (128, 256)
inter_layer_pooling_size: (2, 2)
cnn_kernelsize: (3, 3)
time_pooling_size: 4
rnn_class: !name:speechbrain.nnet.LSTM
rnn_layers: 4
rnn_neurons: 1024
rnn_bidirectional: True
dnn_blocks: 2
dnn_neurons: 1024
emb_size: 128
dec_neurons: 1024
output_neurons: 1000  # index(blank/eos/bos) = 0
joint_dim: 128
blank_index: 0

# Decoding parameters
beam_size: 4
nbest: 1
lm_weight: 0.50

# LM Model parameters
lm_emb_size: 128
lm_activation: !name:torch.nn.LeakyReLU
lm_dropout: 0.0
lm_rnn_layers: 2
lm_rnn_neurons: 2048
lm_dnn_blocks: 1
lm_dnn_neurons: 512

epoch_counter: !new:speechbrain.EpochCounter
    limit: !ref <number_of_epochs>

# Dataloaders
train_loader: !new:speechbrain.data_io.DataLoaderFactory
    csv_file: !ref <csv_train>
    batch_size: !ref <batch_size>
    sentence_sorting: ascending
    output_folder: !ref <output_folder>
    csv_read: [wav, wrd]

valid_loader: !new:speechbrain.data_io.DataLoaderFactory
    csv_file: !ref <csv_valid>
    batch_size: !ref <batch_size_valid>
    sentence_sorting: ascending
    output_folder: !ref <output_folder>
    csv_read: [wav, wrd]

test_clean_loader: !new:speechbrain.data_io.DataLoaderFactory
    csv_file: !ref <csv_test_clean>
    batch_size: !ref <batch_size_valid>
    sentence_sorting: ascending
    output_folder: !ref <output_folder>
    csv_read: [wav, wrd]

test_other_loader: !new:speechbrain.data_io.DataLoaderFactory
    csv_file: !ref <csv_test_other>
    batch_size: !ref <batch_size_valid>
    sentence_sorting: ascending
    output_folder: !ref <output_folder>
    csv_read: [wav, wrd]

normalize: !new:speechbrain.processing.InputNormalization
    norm_type: global

compute_features: !new:speechbrain.lobes.Fbank
    sample_rate: !ref <sample_rate>
    n_fft: !ref <n_fft>
    n_mels: !ref <n_mels>

env_corrupt: !new:speechbrain.lobes.EnvCorrupt
    openrir_folder: !ref <data_folder_rirs>
    babble_prob: 0.0
    reverb_prob: 0.0
    noise_prob: 1.0
    noise_snr_low: 0
    noise_snr_high: 15

augmentation: !new:speechbrain.lobes.TimeDomainSpecAugment
    sample_rate: !ref <sample_rate>
    speeds: [95, 100, 105]

enc: !new:speechbrain.lobes.CRDNN
    input_shape: [null, null, !ref <n_mels>]
    activation: !ref <activation>
    dropout: !ref <dropout>
    cnn_blocks: !ref <cnn_blocks>
    cnn_channels: !ref <cnn_channels>
    cnn_kernelsize: !ref <cnn_kernelsize>
    inter_layer_pooling_size: !ref <inter_layer_pooling_size>
    time_pooling: True
    using_2d_pooling: False
    time_pooling_size: !ref <time_pooling_size>
    rnn_class: !ref <rnn_class>
    rnn_layers: !ref <rnn_layers>
    rnn_neurons: !ref <rnn_neurons>
    rnn_bidirectional: !ref <rnn_bidirectional>
    rnn_re_init: True
    dnn_blocks: !ref <dnn_blocks>
    dnn_neurons: !ref <dnn_neurons>

# For MTL CTC over the encoder
# enc_lin: !new:speechbrain.nnet.Linear
#     input_size: !ref <dnn_neurons>
#     n_neurons: !ref <joint_dim>
#
# ctc_cost: !name:speechbrain.nnet.ctc_loss
#    blank_index: !ref <blank_index>

emb: !new:speechbrain.nnet.Embedding
    num_embeddings: !ref <output_neurons>
    consider_as_one_hot: True
    blank_id: !ref <blank_index>

dec: !new:speechbrain.nnet.GRU
    input_shape: [null, null, !ref <output_neurons> - 1]
    hidden_size: !ref <dec_neurons>
    num_layers: 1
    re_init: True

# For MTL with LM over the decoder
# dec_lin: !new:speechbrain.nnet.linear.Linear
#     input_size: !ref <dec_neurons>
#     n_neurons: !ref <joint_dim>
#     bias: False
#
# ce_cost: !name:speechbrain.nnet.nll_loss
#    label_smoothing: 0.1

Tjoint: !new:speechbrain.nnet.transducer.transducer_joint.Transducer_joint
    joint: concat # joint [sum | concat]
    nonlinearity: !ref <activation>

transducer_lin: !new:speechbrain.nnet.Linear
    input_size: 1024
    n_neurons: !ref <output_neurons>
    bias: False

log_softmax: !new:speechbrain.nnet.Softmax
    apply_log: True

transducer_cost: !name:speechbrain.nnet.transducer_loss
    blank_index: !ref <blank_index>

lm_model: !new:speechbrain.lobes.RNNLM
    output_neurons: !ref <output_neurons>
    embedding_dim: !ref <emb_size>
    activation: !ref <lm_activation>
    dropout: !ref <lm_dropout>
    rnn_layers: !ref <lm_rnn_layers>
    rnn_neurons: !ref <lm_rnn_neurons>
    dnn_blocks: !ref <lm_dnn_blocks>
    dnn_neurons: !ref <lm_dnn_neurons>
    return_hidden: True  # For inference

# for MTL
# update model if any HEAD module is added
modules:
    enc: !ref <enc>
    emb: !ref <emb>
    dec: !ref <dec>
    Tjoint: !ref <Tjoint>
    transducer_lin: !ref <transducer_lin>
    normalize: !ref <normalize>
    env_corrupt: !ref <env_corrupt>
    augmentation: !ref <augmentation>
    lm_model: !ref <lm_model>

# for MTL
# update model if any HEAD module is added
model: !new:torch.nn.ModuleList
    - [!ref <enc>, !ref <emb>, !ref <dec>, !ref <transducer_lin>]

opt_class: !name:torch.optim.Adadelta
    lr: !ref <lr>
    rho: 0.95
    eps: 1.e-8

lr_annealing: !new:speechbrain.nnet.NewBobScheduler
    initial_value: !ref <lr>
    improvement_threshold: 0.0025
    annealing_factor: 0.8
    patient: 0

checkpointer: !new:speechbrain.Checkpointer
    checkpoints_dir: !ref <save_folder>
    recoverables:
        model: !ref <model>
        scheduler: !ref <lr_annealing>
        normalizer: !ref <normalize>
        counter: !ref <epoch_counter>

train_logger: !new:speechbrain.FileTrainLogger
    save_file: !ref <train_log>

error_rate_computer: !name:speechbrain.ErrorRateStats

cer_computer: !name:speechbrain.ErrorRateStats
    split_tokens: True
