# ################################
# Model: 1-D causal CNNTransformer model with log1p mapping
# Authors: Chien-Feng Liao
# ################################

# Seed needs to be set at top of yaml, before objects with parameters are made
seed: 1234
__set_seed: !!python/object/apply:torch.manual_seed [!ref <seed>]

# Basic parameters
data_folder: !PLACEHOLDER
output_folder: !ref results/causalCNNTransformer/<seed>
enhanced_folder: !ref <output_folder>/enhanced/

use_tensorboard: False
tensorboard_logs: !ref results/logs/causalCNNTransformer/<seed>
train_log: !ref <output_folder>/train_log.txt

# Data files
csv_noise: !ref <data_folder>/tr_noise.csv
csv_clean: !ref <data_folder>/tr_clean.csv
csv_valid: !ref <data_folder>/valid.csv
csv_test: !ref <data_folder>/test.csv

# Training Parameters
N_epochs: 50
N_batch: 8
lr: 0.0002
device: cuda:0

# Model Parameters
drop_rate: 0.1
num_blocks: 8
intermediate_size: 512
nhead: 16
causal: True
kernel_size: 3
base_channels: 1024
padding_type: causal

# FFT Parameters
Sample_rate: 16000
N_fft: 512
Win_length: 32
Hop_length: 16

activation: !name:torch.nn.LeakyReLU
output_activation: !name:torch.nn.ReLU
CNN_activation: !new:torch.nn.LeakyReLU

CNN: !new:speechbrain.nnet.containers.Sequential
  - [null, null, !ref <N_fft> // 2 + 1]
  - !name:speechbrain.nnet.Conv1d
    out_channels: !ref <base_channels>
    kernel_size: !ref <kernel_size>
    padding: !ref <padding_type>
  - !name:speechbrain.nnet.LayerNorm
  - !new:torch.nn.LeakyReLU
  - !name:speechbrain.nnet.Conv1d
    out_channels: !ref <base_channels> // 2
    kernel_size: !ref <kernel_size>
    padding: !ref <padding_type>
  - !name:speechbrain.nnet.LayerNorm
  - !new:torch.nn.LeakyReLU
  - !name:speechbrain.nnet.Conv1d
    out_channels: !ref <base_channels> // 8
    kernel_size: !ref <kernel_size>
    padding: !ref <padding_type>
  - !name:speechbrain.nnet.LayerNorm
  - !new:torch.nn.LeakyReLU
  - !name:speechbrain.nnet.Conv1d
    out_channels: !ref <base_channels> // 4
    kernel_size: !ref <kernel_size>
    padding: !ref <padding_type>
  - !name:speechbrain.nnet.LayerNorm
  - !new:torch.nn.LeakyReLU

model: !new:speechbrain.lobes.CNNTransformerSE
  d_model: !ref <base_channels> // 4
  output_size: !ref <N_fft> // 2 + 1
  output_activation: !ref <output_activation>
  activation: !ref <activation>
  dropout: !ref <drop_rate>
  num_layers: !ref <num_blocks>
  d_ffn: !ref <intermediate_size>
  nhead: !ref <nhead>
  causal: !ref <causal>
  custom_emb_module: !ref <CNN>

modules:
  model: !ref <model>

train_loader: !new:speechbrain.data_io.data_io.DataLoaderFactory
  csv_file: !ref <csv_clean>
  batch_size: !ref <N_batch>
  csv_read: [wav]
  cache: False
  num_workers: 1

valid_loader: !new:speechbrain.data_io.data_io.DataLoaderFactory
  csv_file: !ref <csv_valid>
  batch_size: !ref <N_batch>
  csv_read: [wav, target]

test_loader: !new:speechbrain.data_io.data_io.DataLoaderFactory
  csv_file: !ref <csv_test>
  batch_size: !ref <N_batch>
  csv_read: [wav, target]

epoch_counter: !new:speechbrain.utils.epoch_loop.EpochCounter
  limit: !ref <N_epochs>

opt_class: !name:torch.optim.Adam
  lr: !ref <lr>

checkpointer: !new:speechbrain.utils.checkpoints.Checkpointer
  checkpoints_dir: !ref <output_folder>/save
  recoverables:
    counter: !ref <epoch_counter>
    model: !ref <model>

hparams:
  use_tensorboard: !ref <use_tensorboard>
  epoch_counter: !ref <epoch_counter>
  model: !ref <model>
  enhanced_folder: !ref <enhanced_folder>
  Sample_rate: !ref <Sample_rate>
  add_noise: !new:speechbrain.processing.speech_augmentation.AddNoise
    csv_file: !ref <csv_noise>
    snr_low: 0
    snr_high: 40
    pad_noise: False
    start_index: 0
    csv_read: [wav]
  lr_annealing: !new:speechbrain.nnet.schedulers.NewBobScheduler
    initial_value: !ref <lr>
    annealing_factor: 0.5
    improvement_threshold: 0.0
    patient: 5
  compute_cost: !name:speechbrain.nnet.mse_loss
  compute_STFT: !new:speechbrain.processing.features.STFT
    sample_rate: !ref <Sample_rate>
    win_length: !ref <Win_length>
    hop_length: !ref <Hop_length>
    n_fft: !ref <N_fft>
  compute_ISTFT: !new:speechbrain.processing.features.ISTFT
    sample_rate: !ref <Sample_rate>
    win_length: !ref <Win_length>
    hop_length: !ref <Hop_length>
  train_logger: !new:speechbrain.utils.train_logger.FileTrainLogger
    save_file: !ref <train_log>
