repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.5.0  # Use the ref you want to point at
    hooks:
      - id: trailing-whitespace
        types: [file, text]
      - id: end-of-file-fixer
        types: [python]
      - id: requirements-txt-fixer
      - id: mixed-line-ending
        types: [python]
        args: [--fix=no]
      - id: check-added-large-files
        args: [--maxkb=1024]

  - repo: https://github.com/psf/black
    rev: 24.3.0
    hooks:
      - id: black
        types: [python]
        additional_dependencies: ['click==8.1.7']

  - repo: https://github.com/PyCQA/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
        types: [python]

  - repo: https://github.com/adrienverge/yamllint
    rev: v1.35.1
    hooks:
      - id: yamllint

  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.4
    hooks:
      - id: codespell
        args: [--ignore-words=.dict-speechbrain.txt]
        additional_dependencies:
          - tomli

  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
