# .readthedocs.yaml

version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "3.12"

python:
  install:
    - requirements: docs/readthedocs-requirements.txt

# Don't build any extra formats
formats: []
