# .readthedocs.yaml

version: 2

build:
  os: ubuntu-20.04
  tools:
    python: "3.9"

python:
  install:
    - requirements: docs/readthedocs-requirements.txt

# Don't build any extra formats
formats: []
