# ################################
# Model: CNNTransformer for speech enhancement
# https://arxiv.org/abs/2010.13154
#
# Dataset : WHAM!
# ################################
# Basic parameters
# Seed needs to be set at top of yaml, before objects with parameters are made
#
seed: 1234
__set_seed: !apply:torch.manual_seed [!ref <seed>]

# Data params

# the data folder for the wham dataset
# data_folder needs to follow the format:  /yourpath/whamr.
# make sure to use the name whamr at your top folder for the dataset!
data_folder: /yourpath/wham
task: enhancement
dereverberate: False
use_freq_domain: True

# the path for wsj0/si_tr_s/ folder -- only needed if dynamic mixing is used
# e.g. /yourpath/wsj0-processed/si_tr_s/
# you need to convert the original wsj0 to 8k
# you can do this conversion with the script ../meta/preprocess_dynamic_mixing.py
base_folder_dm: /yourpath/wsj0-processed/si_tr_s/

experiment_name: cnntransformer-wham-enhancement-DM
output_folder: !ref results/<experiment_name>/<seed>
train_log: !ref <output_folder>/train_log.txt
save_folder: !ref <output_folder>/save

# the file names should start with whamr instead of whamorg
train_data: !ref <save_folder>/whamorg_tr.csv
valid_data: !ref <save_folder>/whamorg_cv.csv
test_data: !ref <save_folder>/whamorg_tt.csv
skip_prep: False

# Experiment params
auto_mix_prec: True # Set it to True for mixed precision
num_spks: 1 # set to 3 for wsj0-3mix
noprogressbar: False
save_audio: True # Save estimated sources on disk
sample_rate: 8000
n_audio_to_save: 20

# Training parameters
N_epochs: 200
batch_size: 8
lr: 0.0001
clip_grad_norm: 5
loss_upper_lim: 999999  # this is the upper limit for an acceptable loss
# if True, the training sequences are cut to a specified length
limit_training_signal_len: False
# this is the length of sequences if we choose to limit
# the signal length of training sequences
training_signal_len: 32000000

# Set it to True to dynamically create mixtures at training time
dynamic_mixing: True

# Parameters for data augmentation

# rir_path variable points to the directory of the room impulse responses
# e.g. /miniscratch/subakany/rir_wavs
# If the path does not exist, it is created automatically.

use_wavedrop: False
use_speedperturb: True
use_rand_shift: False
min_shift: -8000
max_shift: 8000

speedperturb: !new:speechbrain.lobes.augment.TimeDomainSpecAugment
    perturb_prob: 1.0
    drop_freq_prob: 0.0
    drop_chunk_prob: 0.0
    sample_rate: !ref <sample_rate>
    speeds: [95, 100, 105]

wavedrop: !new:speechbrain.lobes.augment.TimeDomainSpecAugment
    perturb_prob: 0.0
    drop_freq_prob: 1.0
    drop_chunk_prob: 1.0
    sample_rate: !ref <sample_rate>

# loss thresholding -- this thresholds the training loss
threshold_byloss: True
threshold: -30

# Encoder parameters
# N_encoder_out: 256
# out_channels: 256
# kernel_size: 16
# kernel_stride: 8

# Dataloader options
dataloader_opts:
    batch_size: !ref <batch_size>
    num_workers: 1

dataloader_opts_valid:
    batch_size: 1
    num_workers: 1

# Specifying the network
Win_length: 32
Hop_length: 16
N_fft: 512
window_fn: !name:torch.hamming_window

Encoder: !new:speechbrain.processing.features.STFT
    sample_rate: !ref <sample_rate>
    win_length: !ref <Win_length>
    hop_length: !ref <Hop_length>
    n_fft: !ref <N_fft>
    window_fn: !ref <window_fn>

MaskNet: !include:models/CNNTransformer.yaml
    N_fft: !ref <N_fft>

Decoder: !new:speechbrain.processing.features.ISTFT
    sample_rate: !ref <sample_rate>
    win_length: !ref <Win_length>
    hop_length: !ref <Hop_length>
    window_fn: !ref <window_fn>

resynth: !name:speechbrain.processing.signal_processing.resynthesize
    stft: !ref <Encoder>
    istft: !ref <Decoder>

optimizer: !name:torch.optim.Adam
    lr: !ref <lr>
    weight_decay: 0

loss: !name:speechbrain.nnet.losses.mse_loss

lr_scheduler: !new:speechbrain.nnet.schedulers.ReduceLROnPlateau
    factor: 0.5
    patience: 2
    dont_halve_until_epoch: 85

epoch_counter: !new:speechbrain.utils.epoch_loop.EpochCounter
    limit: !ref <N_epochs>

modules:
    masknet: !ref <MaskNet[model]>

save_all_checkpoints: False
checkpointer: !new:speechbrain.utils.checkpoints.Checkpointer
    checkpoints_dir: !ref <save_folder>
    recoverables:
        masknet: !ref <MaskNet[model]>
        counter: !ref <epoch_counter>
        lr_scheduler: !ref <lr_scheduler>

train_logger: !new:speechbrain.utils.train_logger.FileTrainLogger
    save_file: !ref <train_log>
