# ############################################################################
# Model: WavLM + LSTM + CTC loss
# Authors: Luca Della Libera 2023
# ############################################################################

seed: 0
__set_seed: !apply:torch.manual_seed [!ref <seed>]

skip_test: False
skip_ewc: False

# Data preparation
new_locales: [or, ga-IE]
old_locales: [fi]
data_dir: !PLACEHOLDER
max_durations: [600, 600, 600]

# Output directories
output_dir: !ref results/<wavlm_variant>/debug/<seed>
save_dir: !ref <output_dir>/save

# Training parameters
train_batch_size: 2
valid_batch_size: 10
train_num_workers: 6
valid_num_workers: 6

sample_rate: 16000
sorting: ascending
avoid_if_longer_than: 10  # Remove utterances longer than 10s (open microphones)

blank_index: 50258  # For CTC loss (use Whisper BOS as blank)

num_epochs: 2
lr: 0.0001
improvement_threshold: 0.0025
annealing_factor: 0.8
ewc_lambda: 5.0
replay_ratio: 0.1
lwf_lambda: 10.0
lwf_T: 2.0
mask_init: 0.01
mask_threshold: 0.005
num_new_decoder_layers: 1

wavlm_variant: wavlm-base
output_norm: True
freeze: False  # WavLM + LSTM
freeze_encoder: False  # WavLM
freeze_feature_extractor: True  # Feature extractor of WavLM
hidden_size: 1024
num_layers: 2
dropout: 0.0
bidirectional: False

max_target_length: 200  # Must be <= 448 (Whisper maximum target length)
auto_mix_prec: True
gradient_checkpointing: False
ckpt_interval_minutes: 600

normalize_transcripts: True

# Dataloader options
train_dataloader_kwargs:
    batch_size: !ref <train_batch_size>
    num_workers: !ref <train_num_workers>

valid_dataloader_kwargs:
    batch_size: !ref <valid_batch_size>
    num_workers: !ref <valid_num_workers>

# Modules
wavlm: !new:model.ProgressiveWavLM
    source: !ref microsoft/<wavlm_variant>
    save_path: !ref <save_dir>/checkpoint
    output_norm: !ref <output_norm>
    freeze: !ref <freeze>
    freeze_encoder: !ref <freeze_encoder>
    freeze_feature_extractor: !ref <freeze_feature_extractor>
    hidden_size: !ref <hidden_size>
    num_layers: !ref <num_layers>
    dropout: !ref <dropout>
    bidirectional: !ref <bidirectional>

ctc_loss: !name:speechbrain.nnet.losses.ctc_loss
    blank_index: !ref <blank_index>

modules:
    wavlm: !ref <wavlm>

# Optimizers
opt_class: !name:torch.optim.AdamW
    lr: !ref <lr>

lr_annealing: !new:speechbrain.nnet.schedulers.NewBobScheduler
    initial_value: !ref <lr>
    improvement_threshold: !ref <improvement_threshold>
    annealing_factor: !ref <annealing_factor>
    patient: 0

# Performance metrics
wer_computer: !name:speechbrain.utils.metric_stats.ErrorRateStats

cer_computer: !name:speechbrain.utils.metric_stats.ErrorRateStats
    split_tokens: True

# Counters, checkpointers, loggers, etc.
epoch_counter: !new:speechbrain.utils.epoch_loop.EpochCounter
    limit: !ref <num_epochs>

checkpointer: !new:speechbrain.utils.checkpoints.Checkpointer
    checkpoints_dir: !ref <save_dir>
    recoverables:
        model: !ref <wavlm>
        scheduler: !ref <lr_annealing>
        counter: !ref <epoch_counter>

train_logger: !new:speechbrain.utils.train_logger.FileTrainLogger
    save_file: !ref <output_dir>/train_log.txt
