# ################################
# Model: VGG2 + LiGRU with time pooling for efficiency
# Additions: TimeDomainSpecAugment
# Authors: Mirco Ravanelli & Peter Plantinga 2020
# ################################

# Seed needs to be set at top of yaml, before objects with parameters are made
seed: 1234
__set_seed: !apply:torch.manual_seed [!ref <seed>]
output_folder: !ref results/augment_CRDNN_selfattention/<seed>
wer_file: !ref <output_folder>/wer.txt
save_folder: !ref <output_folder>/save
train_log: !ref <output_folder>/train_log.txt

# Data files
data_folder: !PLACEHOLDER  # e.g. /path/to/TIMIT
csv_train: !ref <data_folder>/train.csv
csv_valid: !ref <data_folder>/dev.csv
csv_test: !ref <data_folder>/test.csv

# Training parameters
number_of_epochs: 55
batch_size: 8
lr: 1
device: 'cuda:0'
ddp_procs: 0  # Set to number of GPUs if multi-gpu

# Feature parameters
sample_rate: 16000
n_fft: 400
n_mels: 40

# Model parameters
activation: !name:torch.nn.GELU
dropout: 0.15
cnn_blocks: 2
cnn_channels: (128, 256)
cnn_kernelsize: (3, 3)
time_pooling: True
rnn_layers: 3
rnn_neurons: 512
rnn_bidirectional: True
dnn_blocks: 2
dnn_neurons: 512
self_attention: True
self_attention_layers: 1
self_attention_num_heads: 128
self_attention_model_dim: 256
self_attention_hidden_dim: 1024
dnn_postionalwise: False

# Outputs
output_neurons: 40
blank_index: !ref <output_neurons> - 1

train_loader: !new:speechbrain.data_io.DataLoaderFactory
    csv_file: !ref <csv_train>
    batch_size: !ref <batch_size>
    sentence_sorting: ascending
    output_folder: !ref <output_folder>
    csv_read: [wav, phn]

valid_loader: !new:speechbrain.data_io.DataLoaderFactory
    csv_file: !ref <csv_valid>
    batch_size: !ref <batch_size>
    sentence_sorting: ascending
    output_folder: !ref <output_folder>
    csv_read: [wav, phn]

test_loader: !new:speechbrain.data_io.DataLoaderFactory
    csv_file: !ref <csv_test>
    batch_size: !ref <batch_size>
    sentence_sorting: ascending
    output_folder: !ref <output_folder>
    csv_read: [wav, phn]

model: !new:speechbrain.lobes.models.CRDNN_selfatt.CRDNN
    input_shape: [null, null, !ref <n_mels>]
    activation: !ref <activation>
    dropout: !ref <dropout>
    cnn_blocks: !ref <cnn_blocks>
    cnn_channels: !ref <cnn_channels>
    cnn_kernelsize: !ref <cnn_kernelsize>
    time_pooling: !ref <time_pooling>
    self_attention: !ref <self_attention>
    self_attention_layers: !ref <self_attention_layers>
    self_attention_num_heads: !ref <self_attention_num_heads>
    self_attention_model_dim: !ref <self_attention_model_dim>
    self_attention_hidden_dim: !ref <self_attention_hidden_dim>
    rnn_layers: !ref <rnn_layers>
    rnn_neurons: !ref <rnn_neurons>
    rnn_bidirectional: !ref <rnn_bidirectional>
    dnn_postionalwise: <dnn_postionalwise>
    dnn_blocks: !ref <dnn_blocks>
    dnn_neurons: !ref <dnn_neurons>

output: !new:speechbrain.nnet.linear.Linear
    input_size: !ref <dnn_neurons> * 2
    n_neurons: !ref <output_neurons>
    bias: True

optim:
    optimizer: !new:torch.optim.Adadelta
        params: !apply:speechbrain.collect_params
            - !ref <model>
            - !ref <output>
        lr: !ref <lr>
        rho: 0.95

jit_modules:
    model: !ref <model>

hparams:
    wer_file: !ref <wer_file>
    output: !ref <output>
    epoch_counter: !new:speechbrain.utils.epoch_loop.EpochCounter
        limit: !ref <number_of_epochs>
    log_softmax: !new:speechbrain.nnet.activations.Softmax
        apply_log: True
    lr_annealing: !new:speechbrain.nnet.NewBobScheduler
        initial_value: !ref <lr>
        improvement_threshold: 0.0025
        annealing_factor: 0.8
        patient: 0
    normalize: !new:speechbrain.processing.features.InputNormalization
        norm_type: global
    augmentation: !new:speechbrain.lobes.augment.tdsa.TimeDomainSpecAugment
        sample_rate: !ref <sample_rate>
        speeds: [95, 100, 105]
    compute_features: !new:speechbrain.lobes.features.fbank.Fbank
        sample_rate: !ref <sample_rate>
        n_fft: !ref <n_fft>
        n_mels: !ref <n_mels>
    compute_cost: !name:speechbrain.nnet.losses.ctc_loss
        blank_index: !ref <blank_index>
    train_logger: !new:speechbrain.utils.train_logger.FileTrainLogger
        save_file: !ref <train_log>
    ctc_stats: !name:speechbrain.MetricStats
        metric: !name:speechbrain.nnet.ctc_loss
            blank_index: !ref <blank_index>
            reduction: batch
    per_stats: !name:speechbrain.ErrorRateStats
    checkpointer: !new:speechbrain.utils.checkpoints.Checkpointer
        checkpoints_dir: !ref <save_folder>
        recoverables:
            model: !ref <model>
            output: !ref <output>
            optimizer: !ref <optim.optimizer>
            counter: !ref <hparams.epoch_counter>
            scheduler: !ref <hparams.lr_annealing>
            normalizer: !ref <hparams.normalize>
