###################################################
# Classification of P300 of EPFLP300 MOABB dataset using EEGNet.
# EEGNet from https://doi.org/10.1088/1741-2552/aace8c.
# EPFLP300 from .
#
# Author
# ------
# Davide Borra, 2022
# Mirco Ravanelli, 2022
# Francesco Paissan, 2022
###################################################
seed: 1234
__set_torchseed: !apply:torch.manual_seed [!ref <seed>]

# DIRECTORIES
data_folder: !PLACEHOLDER  #'/path/to/dataset'. The dataset will be automatically downloaded in this folder
cached_data_folder: !PLACEHOLDER  #'/path/to/pickled/dataset'
output_folder: !ref results/MOABB/EEGNet_EPFLP300/<seed>


# DATASET HPARS
# Defining the MOABB dataset.
dataset: !new:moabb.datasets.EPFLP300
to_download: False
to_prepare: False # set to True if you want to always prepare data
# data preparation may be slow if the dataset contains many channels with long recordings
# eventually, save the prepared dataset (save_prepared_dataset: True) and set to_prepare to False
# to optionally load previously prepared data (cached dataset in pkl files)
save_prepared_dataset: True # set to True if you want to save the prepared dataset as a pkl file to load and use afterwards

data_iterator_name: !PLACEHOLDER
target_subject_idx: !PLACEHOLDER
target_session_idx: !PLACEHOLDER
events_to_load: null # all events will be loaded
original_sample_rate: 512 # Original sampling rate provided by dataset authors
sample_rate: 128 # Target sampling rate (Hz)
fmin: 0.14 # band-pass filtering cut-off frequencies
fmax: 21.9

n_classes: 2

# tmin, tmax respect to stimulus onset that define the interval attribute of the dataset class
# trial begins (0 s), cue (2 s, 1.25 s long); each trial is 6 s long
# dataset interval starts from 2
# -->tmin tmax are referred to this start value (e.g., tmin=0.5 corresponds to 2.5 s)
tmin: 0.
tmax: 0.8
n_steps_channel_selection: 3 # number of steps used when selecting adjacent channels from a seed channel (default at Cz)

T: !apply:math.ceil
    - !ref <sample_rate> * (<tmax> - <tmin>)
C: 32
n_train_examples: 100  # it will be replaced in the train script
# We here specify how to perfom test:
# - If test_with: 'last' we perform test with the latest model.
# - if test_with: 'best, we perform test with the best model (according to the metric specified in test_key)
# The variable avg_models can be used to average the parameters of the last (or best) N saved models before testing.
# This can have a regularization effect. If avg_models: 1, the last (or best) model is used directly.
test_with: 'last' # 'last' or 'best'
test_key: "f1" # Possible opts: "loss", "f1", "auc", "acc"
avg_models: 2 # checkpoints to average

f1: !name:sklearn.metrics.f1_score
    pos_label: 1
acc: !name:sklearn.metrics.balanced_accuracy_score
cm: !name:sklearn.metrics.confusion_matrix
metrics:
    f1: !ref <f1>
    acc: !ref <acc>
    cm: !ref <cm>

# TRAINING HPARS
number_of_epochs: 726 # number of training epochs
#number_of_epochs_: 8.0 # number of training epochs
#number_of_epochs: !ref <number_of_epochs_> * 100  # number of training epochs
lr: 0.0001
# Learning rate scheduling (cyclic learning rate is used here)
max_lr: !ref <lr> # Upper bound of the cycle (max value of the lr)
base_lr: 0.00000001 # Lower bound in the cycle (min value of the lr)

step_size_multiplier: 5 #from 2 to 8
step_size: !apply:round
    - !ref <step_size_multiplier> * <n_train_examples> / <batch_size>

label_smoothing: 0.0

loss: !name:speechbrain.nnet.losses.nll_loss
    label_smoothing: !ref <label_smoothing>

optimizer: !name:torch.optim.Adam
    lr: !ref <lr>
epoch_counter: !new:speechbrain.utils.epoch_loop.EpochCounter  # epoch counter
    limit: !ref <number_of_epochs>
batch_size_exponent: 4
batch_size: !ref 2 ** <batch_size_exponent> #64
valid_ratio: 0.2

# DATA AUGMENTATION
# cutcat (disabled when min_num_segments=max_num_segments=1)
max_num_segments: 2 # 1-6
cutcat: !new:speechbrain.processing.speech_augmentation.CutCat
    min_num_segments: 2
    max_num_segments: !ref <max_num_segments>

# random amplitude gain between 0.5-1.5 uV (disabled when amp_delta=0.)
amp_delta: 0.4985 # 0.-0.5
rand_amp: !new:speechbrain.processing.speech_augmentation.RandAmp
    amp_low: !ref 1 - <amp_delta>
    amp_high: !ref 1 + <amp_delta>

# random shifts between -300 ms to 300 ms (disabled when shift_delta=0.)
shift_delta_: 0 # 0-25
shift_delta: !ref 1e-2 * <shift_delta_> # 0.250 # 0.-0.25 with steps of 0.01
min_shift: !apply:math.floor
    - !ref 0 - <sample_rate> * <shift_delta>
max_shift: !apply:math.floor
    - !ref 0 + <sample_rate> * <shift_delta>
time_shift: !new:speechbrain.processing.speech_augmentation.RandomShift
    min_shift: !ref <min_shift>
    max_shift: !ref <max_shift>
    dim: 1

# injection of gaussian white noise
snr_white_low: 0.35 #0-10
snr_white_delta: 15 #0-10
snr_white_high: !ref <snr_white_low> + <snr_white_delta>
add_noise_white: !new:speechbrain.processing.speech_augmentation.AddNoise
    snr_low: !ref <snr_white_low>
    snr_high: !ref <snr_white_high>

repeat_augment: 1 # 1 for da enabled, 0 for da disabled
augment: !new:speechbrain.processing.augmentation.Augmenter
    parallel_augment: True
    concat_original: True
    parallel_augment_fixed_bs: True
    repeat_augment: !ref <repeat_augment>
    shuffle_augmentations: True
    min_augmentations: 4
    max_augmentations: 4
    cutcat: !ref <cutcat>
    rand_amp: !ref <rand_amp>
    time_shift: !ref <time_shift>
    augment_noise: !ref <add_noise_white>

# DATA NORMALIZATION
dims_to_normalize: 1 # 1 (time) or 2 (EEG channels)
normalize: !name:speechbrain.processing.signal_processing.mean_std_norm
    dims: !ref <dims_to_normalize>

# MODEL: BASELINE EEGNET
input_shape: [null, !ref <T>, !ref <C>, null]
#cnn_temporal_kernels_exponent: 3
#cnn_temporal_kernels: !ref 2 ** <cnn_temporal_kernels_exponent> #8  # number of temporal filters in the temporal conv. layer
cnn_temporal_kernels: 39
cnn_temporal_kernelsize: 29 # kernel size of the 2d temporal convolution
# kernel size learning temporal patterns within 100 ms, 150 ms,...,750 ms
#cnn_temporal_kernelsize_: 10
#cnn_temporal_kernelsize: !apply:round
#  - !ref <cnn_temporal_kernelsize_> * <sample_rate> / (2 * 10)
#cnn_temporal_kernelsize_s: 0.5
#cnn_temporal_kernelsize: !apply:round
#  - !ref <cnn_temporal_kernelsize_s> * <sample_rate>

cnn_spatial_depth_multiplier: 1  # depth multiplier for the spatial depthwise conv. layer
cnn_spatial_max_norm: 1.  # kernel max-norm constaint of the spatial depthwise conv. layer
cnn_spatial_pool: 4
#

cnn_septemporal_depth_multiplier: 1  # depth multiplier for the separable temporal conv. layer
cnn_septemporal_point_kernels_ratio_: 7
cnn_septemporal_point_kernels_ratio: !ref <cnn_septemporal_point_kernels_ratio_> / 4
## number of temporal filters in the separable temporal conv. layer
cnn_septemporal_point_kernels_: !ref <cnn_temporal_kernels> * <cnn_spatial_depth_multiplier> * <cnn_septemporal_depth_multiplier>
cnn_septemporal_point_kernels: !apply:math.ceil
    - !ref <cnn_septemporal_point_kernels_ratio> * <cnn_septemporal_point_kernels_> + 1

# kernel size learning temporal patterns within 100 ms, 150 ms,...,750 ms
#cnn_septemporal_kernelsize_s: 0.5
#cnn_septemporal_kernelsize: !apply:round
#  - !ref <cnn_septemporal_kernelsize_s> * <sample_rate> / <cnn_spatial_pool>
#cnn_septemporal_kernelsize_: 10
#cnn_septemporal_kernelsize: !apply:round
#  - !ref <cnn_septemporal_kernelsize_> * <sample_rate> / (2 * 10 * <cnn_spatial_pool>)
cnn_septemporal_kernelsize_: 24 # @ 32 Hz
max_cnn_spatial_pool: 4
cnn_septemporal_kernelsize: !apply:round
    - !ref <cnn_septemporal_kernelsize_> * <max_cnn_spatial_pool> / <cnn_spatial_pool>


#cnn_septemporal_kernelsize_: 5
#cnn_septemporal_kernelsize: !apply:round
#  - !ref <cnn_septemporal_kernelsize_> * <sample_rate> / (10 * <cnn_spatial_pool>)
#cnn_septemporal_kernelsize_: 62
#cnn_septemporal_kernelsize: !apply:round
#  - !ref <cnn_septemporal_kernelsize_> / <cnn_spatial_pool>
#cnn_septemporal_kernelsize: 16

cnn_septemporal_pool: 7
cnn_pool_type: 'avg'

dense_max_norm: 0.25  # kernel max-norm constaint of the dense layer

dropout: 0.3847  # dropout rate
activation_type: 'elu'

model: !new:speechbrain.lobes.models.EEGNet.EEGNet
    input_shape: !ref <input_shape>
    cnn_temporal_kernels: !ref <cnn_temporal_kernels>
    cnn_temporal_kernelsize: [!ref <cnn_temporal_kernelsize>, 1]
    cnn_spatial_depth_multiplier: !ref <cnn_spatial_depth_multiplier>
    cnn_spatial_max_norm: !ref <cnn_spatial_max_norm>
    cnn_spatial_pool: [!ref <cnn_spatial_pool>, 1]
    cnn_septemporal_depth_multiplier: !ref <cnn_septemporal_depth_multiplier>
    cnn_septemporal_point_kernels: !ref <cnn_septemporal_point_kernels>
    cnn_septemporal_kernelsize: [!ref <cnn_septemporal_kernelsize>, 1]
    cnn_septemporal_pool: [!ref <cnn_septemporal_pool>, 1]
    cnn_pool_type: !ref <cnn_pool_type>
    activation_type: !ref <activation_type>
    dense_max_norm: !ref <dense_max_norm>
    dropout: !ref <dropout>
    dense_n_neurons: !ref <n_classes>

lr_annealing: !new:speechbrain.nnet.schedulers.CyclicLRScheduler
    base_lr: !ref <base_lr>
    max_lr: !ref <max_lr>
    step_size: !ref <step_size>
