# ################################
# Model: ConvTasnet for source separation
# Data : Minimal Example
# Author: Cem Subakan
# ################################


# Basic parameters
# Seed needs to be set at top of yaml, before objects with parameters are made
seed: 1234
__set_seed: !!python/object/apply:torch.manual_seed [!ref <seed>]
use_tensorboard: False
tensorboard_logs: runs/minimal_example
output_folder: !ref results/conv_tasnet/<seed>
save_folder: !ref <output_folder>/save
train_log: !ref <output_folder>/train_log.txt
tr_csv: >
        ../../../../samples/audio_samples/sourcesep_samples/
        minimal_example_convtasnet_tr.csv
cv_csv: >
        ../../../../samples/audio_samples/sourcesep_samples/
        minimal_example_convtasnet_cv.csv
tt_csv: >
        ../../../../samples/audio_samples/sourcesep_samples/
        minimal_example_convtasnet_tt.csv
data_folder: ../../../../samples/audio_samples/sourcesep_samples

# Neural Parameters
N_epochs: 150
N_batch: 1
lr: 0.002
train_onthefly: False
loss_fn: 'sisnr'
progressbar: True

train_loader: !new:speechbrain.data_io.data_io.DataLoaderFactory
    csv_file: !ref <tr_csv>
    batch_size: !ref <N_batch>
    sentence_sorting: random
    csv_read: [mix_wav, s1_wav, s2_wav]
    replacements:
        $data_folder: !ref <data_folder>

val_loader: !new:speechbrain.data_io.data_io.DataLoaderFactory
    csv_file: !ref <cv_csv>
    batch_size: !ref <N_batch>
    sentence_sorting: random
    csv_read: [mix_wav, s1_wav, s2_wav]
    replacements:
        $data_folder: !ref <data_folder>


test_loader: !new:speechbrain.data_io.data_io.DataLoaderFactory
    csv_file: !ref <tt_csv>
    batch_size: !ref <N_batch>
    sentence_sorting: random
    csv_read: [mix_wav, s1_wav, s2_wav]
    replacements:
        $data_folder: !ref <data_folder>

augmentation: !new:speechbrain.lobes.augment.tdsa.TimeDomainSpecAugment
    sample_rate: 8000
    speeds: [95, 100, 105]


MaskNet: !new:speechbrain.lobes.models.conv_tasnet.MaskNet
    N: 32
    B: 32
    H: 32
    P: 3
    X: 1
    R: 2
    C: 2
    norm_type: 'gLN'
    causal: False
    mask_nonlinear: 'relu'

Encoder: !new:speechbrain.lobes.models.conv_tasnet.Encoder
    L: 21
    N: 32

Decoder: !new:speechbrain.lobes.models.conv_tasnet.Decoder
    L: 20

optimizer: !new:speechbrain.nnet.optimizers.Adam_Optimizer
    learning_rate: !ref <lr>

epoch_counter: !new:speechbrain.utils.epoch_loop.EpochCounter
    limit: !ref <N_epochs>

checkpointer: !new:speechbrain.utils.checkpoints.Checkpointer
    checkpoints_dir: !ref <save_folder>
    recoverables:
        encoder: !ref <Encoder>
        decoder: !ref <Decoder>
        masknet: !ref <MaskNet>
        optimizer: !ref <optimizer>
        counter: !ref <epoch_counter>

train_logger: !new:speechbrain.utils.train_logger.FileTrainLogger
    save_file: !ref <train_log>
    summary_fns:
        SISNR: !name:speechbrain.utils.train_logger.summarize_error_rate
