output_folder: !PLACEHOLDER
data_folder: ../../../samples
csv_file: !ref <data_folder>/audio_samples/csv_example.csv
sample_rate: 16000
batch_size: 2

sample_data: !speechbrain.data_io.data_io.DataLoaderFactory
    csv_file: !ref <csv_file>
    batch_size: !ref <batch_size>
    csv_read: [wav]
    replacements:
        $data_folder: !ref <data_folder>/audio_samples

add_babble: !speechbrain.processing.speech_augmentation.AddBabble
    speaker_count: 4 # Must set batch size to 5 or more
    snr_low: 10
    snr_high: 10

add_reverb: !speechbrain.processing.speech_augmentation.AddReverb
    csv_file: !ref <data_folder>/rir_samples/rirs_rel.csv
    order: random
    replacements:
        $rir_folder: !ref <data_folder>/rir_samples

add_noise: !speechbrain.processing.speech_augmentation.AddNoise
    csv_file: !ref <data_folder>/noise_samples/noise_rel.csv
    order: random
    snr_low: 10
    snr_high: 10
    pad_noise: False
    replacements:
        $noise_folder: !ref <data_folder>/noise_samples

drop_freq: !speechbrain.processing.speech_augmentation.DropFreq
    drop_freq_low: 0.1
    drop_freq_high: 0.9
    drop_count_low: 1
    drop_count_high: 3
    drop_width: 0.05

drop_chunk: !speechbrain.processing.speech_augmentation.DropChunk
    drop_length_low: 1000
    drop_length_high: 2000
    drop_count_low: 3
    drop_count_high: 5
    drop_start: 0
    drop_end: null

do_clip: !speechbrain.processing.speech_augmentation.DoClip
    clip_low: 0.1
    clip_high: 0.2

speed_perturb: !speechbrain.processing.speech_augmentation.SpeedPerturb
    orig_freq: !ref <sample_rate>
    speeds: [9, 11]

save: !speechbrain.data_io.data_io.TensorSaver
    sampling_rate: !ref <sample_rate>
    save_format: flac
    parallel_write: True
    save_folder: !ref <output_folder>/save
