# ################################
# Model: VGG2 + LiGRU with time pooling for efficiency
# Additions: TimeDomainSpecAugment
# Authors: Mirco Ravanelli & Peter Plantinga 2020
# ################################

# Seed needs to be set at top of yaml, before objects with parameters are made
seed: 42
__set_seed: !apply:torch.manual_seed [!ref <seed>]
output_folder: !ref results/augment_noise_CRDNN/<seed>
wer_file: !ref <output_folder>/wer.txt
save_folder: !ref <output_folder>/save
train_log: !ref <output_folder>/train_log.txt

# Data files
data_folder: /media/sam/HitachiX360/TIMIT/  # e.g. /path/to/TIMIT

# Training parameters
number_of_epochs: 50
batch_size: 8
lr: 1.0

# For DDP, use `python -m speechbrain.ddp experiment.py` to launch experiment
# These options will be set by that script, and will override these.
device: 'cuda:0'
multigpu_count: 0  # Set to number of GPUs if multi-gpu
multigpu_backend: null  # ['data_parallel', 'ddp_nccl', 'ddp_gloo', 'ddp_mpi']

# Feature parameters
sample_rate: 16000
n_fft: 400
n_mels: 40

# Model parameters
activation: !name:torch.nn.LeakyReLU
dropout: 0.15
cnn_blocks: 2
cnn_channels: (128, 256)
cnn_kernelsize: (3, 3)
rnn_layers: 4
rnn_neurons: 512
rnn_bidirectional: True
dnn_blocks: 2
dnn_neurons: 512

# Outputs
output_neurons: 40
blank_index: !ref <output_neurons> - 1

epoch_counter: !new:speechbrain.utils.epoch_loop.EpochCounter
    limit: !ref <number_of_epochs>

train_examples: !apply:speechbrain.data_io.data_io.load_json
    json_path: !ref <data_folder>/train.json
dev_examples: !apply:speechbrain.data_io.data_io.load_json
    json_path: !ref <data_folder>/dev.json
test_examples: !apply:speechbrain.data_io.data_io.load_json
    json_path: !ref <data_folder>/test.json

label_encoder: !apply:speechbrain.data_io.encoders.CTCTextEncoder.fit_from_yaml
    data_collections: [!ref <train_examples>, !ref <dev_examples>]
    supervision: phn
    blank_encoding: !ref <blank_index>
    sup_transform: !name:speechbrain.utils.data_utils.split_by_whitespace

text_pipeline: !new:speechbrain.utils.data_utils.FuncPipeline
    - !name:speechbrain.utils.data_utils.split_by_whitespace
    - !ref <label_encoder.encode_sequence>
    - !name:speechbrain.data_io.data_io.to_longTensor

audio_pipeline: !new:speechbrain.utils.data_utils.FuncPipeline
    - !name:speechbrain.data_io.data_io.read_audio

data_tf:
    - !ref <text_pipeline>
    - !ref <audio_pipeline>

train_data: !apply:speechbrain.data_io.datasets.SegmentedDataset.from_extended_yaml
    examples: !ref <train_examples>
    data_transforms: !ref <data_tf>

valid_data: !apply:speechbrain.data_io.datasets.SegmentedDataset.from_extended_yaml
    examples: !ref <dev_examples>
    data_transforms: !ref <data_tf>

test_data: !apply:speechbrain.data_io.datasets.SegmentedDataset.from_extended_yaml
    examples: !ref <test_examples>
    data_transforms: !ref <data_tf>


sampler: !new:speechbrain.data_io.sampler.OrderedSampler
    data_source: !ref <train_data>
    sorting: ascending

train_loader: !new:speechbrain.data_io.dataloader.SaveableDataLoader
    dataset: !ref <train_data>
    batch_size: !ref <batch_size>
    sampler: !ref <sampler>
    collate_fn: !name:speechbrain.data_io.batch.PaddedBatch

valid_loader: !new:speechbrain.data_io.dataloader.SaveableDataLoader
    dataset: !ref <valid_data>
    batch_size: !ref <batch_size>
    collate_fn: !name:speechbrain.data_io.batch.PaddedBatch

test_loader: !new:speechbrain.data_io.dataloader.SaveableDataLoader
    dataset: !ref <test_data>
    batch_size: !ref <batch_size>
    collate_fn: !name:speechbrain.data_io.batch.PaddedBatch

normalize: !new:speechbrain.processing.features.InputNormalization
    norm_type: global

augmentation: !new:speechbrain.lobes.augment.TimeDomainSpecAugment
    sample_rate: !ref <sample_rate>
    speeds: [95, 100, 105]

# Can be removed to improve speed
env_corrupt: !new:speechbrain.lobes.augment.EnvCorrupt
    openrir_folder: !ref <data_folder>
    babble_prob: 0.0
    reverb_prob: 0.0
    noise_prob: 1.0
    noise_snr_low: 0
    noise_snr_high: 15

compute_features: !new:speechbrain.lobes.features.Fbank
    sample_rate: !ref <sample_rate>
    n_fft: !ref <n_fft>
    n_mels: !ref <n_mels>

model: !new:speechbrain.lobes.models.CRDNN.CRDNN
    input_shape: [null, null, !ref <n_mels>]
    activation: !ref <activation>
    dropout: !ref <dropout>
    cnn_blocks: !ref <cnn_blocks>
    cnn_channels: !ref <cnn_channels>
    cnn_kernelsize: !ref <cnn_kernelsize>
    time_pooling: True
    rnn_layers: !ref <rnn_layers>
    rnn_neurons: !ref <rnn_neurons>
    rnn_bidirectional: !ref <rnn_bidirectional>
    dnn_blocks: !ref <dnn_blocks>
    dnn_neurons: !ref <dnn_neurons>

output: !new:speechbrain.nnet.linear.Linear
    input_size: !ref <dnn_neurons>
    n_neurons: !ref <output_neurons>
    bias: True

log_softmax: !new:speechbrain.nnet.activations.Softmax
    apply_log: True

opt_class: !name:torch.optim.Adadelta
    rho: 0.95
    lr: !ref <lr>
    eps: 1.e-8

lr_annealing: !new:speechbrain.nnet.schedulers.NewBobScheduler
    initial_value: !ref <lr>
    improvement_threshold: 0.0025
    annealing_factor: 0.8
    patient: 0

modules:
    model: !ref <model>
    output: !ref <output>
    normalize: !ref <normalize>
    #env_corrupt: !ref <env_corrupt>

jit_module_keys: [model]

checkpointer: !new:speechbrain.utils.checkpoints.Checkpointer
    checkpoints_dir: !ref <save_folder>
    recoverables:
        model: !ref <model>
        output: !ref <output>
        scheduler: !ref <lr_annealing>
        normalizer: !ref <normalize>
        counter: !ref <epoch_counter>

compute_cost: !name:speechbrain.nnet.losses.ctc_loss
    blank_index: !ref <blank_index>

train_logger: !new:speechbrain.utils.train_logger.FileTrainLogger
    save_file: !ref <train_log>

ctc_stats: !name:speechbrain.utils.metric_stats.MetricStats
    metric: !name:speechbrain.nnet.losses.ctc_loss
        blank_index: !ref <blank_index>
        reduction: batch

per_stats: !name:speechbrain.utils.metric_stats.ErrorRateStats
