import torch
from unittest.mock import patch


def test_curriculum_speech_dataset():
    from speechbrain.dataio.dataio import read_audio
    from speechbrain.dataio.dataset import DynamicItemDataset
    from speechbrain.dataio.curriculum import CurriculumSpeechDataset
    import re

    sample_data = {
        "1034-121119-0046": {
            "snt_id": "1034-121119-0046",
            "duration": 2.46,
            "spk_id": "1034-121119",
            "wrd": [
                "",
                "YOU",
                "WILL",
                "EXCUSE",
                "THIS",
                "POOR",
                "FELLOW",
                "MADAME",
                "",
            ],
            "wav": "tests/samples/curriculum/1034-121119-0046.flac",
            "char": "YOU WILL EXCUSE THIS POOR FELLOW MADAME",
            "wrd_start": [0.0, 0.29, 0.39, 0.5, 0.92, 1.11, 1.37, 1.71, 2.21],
            "wrd_end": [0.29, 0.39, 0.5, 0.92, 1.11, 1.37, 1.71, 2.21, 2.46],
            "wrd_count": 9,
            "phn": [
                "sil",
                "Y",
                "UW1",
                "W",
                "AH0",
                "L",
                "IH0",
                "K",
                "S",
                "K",
                "Y",
                "UW1",
                "Z",
                "DH",
                "IH0",
                "S",
                "P",
                "UW1",
                "R",
                "F",
                "EH1",
                "L",
                "OW0",
                "M",
                "AH0",
                "D",
                "AE1",
                "M",
                "sp",
                "",
            ],
            "phn_start": [
                0.0,
                0.29,
                0.35,
                0.39,
                0.42,
                0.45,
                0.5,
                0.55,
                0.6,
                0.68,
                0.74,
                0.79,
                0.86,
                0.92,
                0.98,
                1.04,
                1.11,
                1.22,
                1.31,
                1.37,
                1.48,
                1.55,
                1.64,
                1.71,
                1.81,
                1.85,
                1.91,
                2.08,
                2.21,
                2.44,
            ],
            "phn_end": [
                0.29,
                0.35,
                0.39,
                0.42,
                0.45,
                0.5,
                0.55,
                0.6,
                0.68,
                0.74,
                0.79,
                0.86,
                0.92,
                0.98,
                1.04,
                1.11,
                1.22,
                1.31,
                1.37,
                1.48,
                1.55,
                1.64,
                1.71,
                1.81,
                1.85,
                1.91,
                2.08,
                2.21,
                2.44,
                2.46,
            ],
            "phn_count": 30,
        },
        "1034-121119-0022": {
            "snt_id": "1034-121119-0022",
            "duration": 2.54,
            "spk_id": "1034-121119",
            "wrd": [
                "",
                "AND",
                "HER",
                "GLANCE",
                "WAS",
                "TURNED",
                "TOWARDS",
                "HEAVEN",
                "",
            ],
            "wav": "tests/samples/curriculum/1034-121119-0022.flac",
            "char": "AND HER GLANCE WAS TURNED TOWARDS HEAVEN",
            "wrd_start": [0.0, 0.52, 0.66, 0.75, 1.12, 1.27, 1.59, 1.95, 2.32],
            "wrd_end": [0.52, 0.66, 0.75, 1.12, 1.27, 1.59, 1.95, 2.32, 2.54],
            "wrd_count": 9,
            "phn": [
                "sil",
                "AE1",
                "N",
                "D",
                "HH",
                "ER0",
                "G",
                "L",
                "AE1",
                "N",
                "S",
                "W",
                "AH0",
                "Z",
                "T",
                "ER1",
                "N",
                "D",
                "T",
                "AH0",
                "W",
                "AO1",
                "R",
                "D",
                "Z",
                "HH",
                "EH1",
                "V",
                "AH0",
                "N",
                "sp",
                "",
            ],
            "phn_start": [
                0.0,
                0.52,
                0.59,
                0.63,
                0.66,
                0.69,
                0.75,
                0.81,
                0.89,
                0.96,
                1.05,
                1.12,
                1.16,
                1.2,
                1.27,
                1.4,
                1.51,
                1.56,
                1.59,
                1.63,
                1.69,
                1.75,
                1.78,
                1.85,
                1.91,
                1.95,
                2.02,
                2.07,
                2.14,
                2.19,
                2.32,
                2.52,
            ],
            "phn_end": [
                0.52,
                0.59,
                0.63,
                0.66,
                0.69,
                0.75,
                0.81,
                0.89,
                0.96,
                1.05,
                1.12,
                1.16,
                1.2,
                1.27,
                1.4,
                1.51,
                1.56,
                1.59,
                1.63,
                1.69,
                1.75,
                1.78,
                1.85,
                1.91,
                1.95,
                2.02,
                2.07,
                2.14,
                2.19,
                2.32,
                2.52,
                2.54,
            ],
            "phn_count": 32,
        },
    }
    dataset = DynamicItemDataset(sample_data)
    test_generator = torch.Generator()
    test_generator.manual_seed(42)
    curriculum_dataset = CurriculumSpeechDataset(
        from_dataset=dataset,
        min_words=1,
        max_words=2,
        generator=test_generator,
    )
    curriculum_dataset.set_output_keys(
        [
            "wrd_count",
            "sig",
            "wrd_start",
            "wrd_end",
            "phn_start",
            "phn_end",
            "wrd",
            "char",
            "phn",
        ]
    )
    assert len(curriculum_dataset) == 2
    for item in curriculum_dataset:
        assert 1 <= len(item["wrd"]) <= 2
        char_words = re.split(r"\s+", item["char"])
        clean_words = [word for word in item["wrd"] if word]
        assert char_words == clean_words
    curriculum_dataset_iter = iter(curriculum_dataset)
    item = next(curriculum_dataset_iter)
    assert item["char"] == "EXCUSE"
    assert item["wrd"] == ["EXCUSE"]
    assert item["phn"] == [
        "IH0",
        "K",
        "S",
        "K",
        "Y",
        "UW1",
        "Z",
    ]
    assert item["wrd_count"] == 1
    file_name = "tests/samples/curriculum/1034-121119-0046.flac"
    wav = read_audio(file_name)
    assert item["sig"].allclose(wav[8000:14720])

    item = next(curriculum_dataset_iter)
    assert item["char"] == "TOWARDS HEAVEN"
    assert item["wrd"] == ["TOWARDS", "HEAVEN"]
    file_name = "tests/samples/curriculum/1034-121119-0022.flac"
    wav = read_audio(file_name)
    assert item["sig"].allclose(wav[25440:37120])
