# Basic parameters
# Seed needs to be set at top of yaml, before objects with parameters are made
seed: 1234
__set_seed: !!python/object/apply:torch.manual_seed [!ref <seed>]

# Data files
data_folder: !PLACEHOLDER
csv_train: !ref <data_folder>/train.csv
csv_valid: !ref <data_folder>/dev.csv
csv_test: !ref <data_folder>/test.csv

# Neural Parameters
N_epochs: 5
N_batch: 2
lr: 0.004

train_loader: !new:speechbrain.DataLoaderFactory
    csv_file: !ref <csv_train>
    batch_size: !ref <N_batch>
    csv_read: [wav]
    sentence_sorting: random
    replacements:
        $data_folder: !ref <data_folder>

valid_loader: !new:speechbrain.DataLoaderFactory
    csv_file: !ref <csv_valid>
    batch_size: !ref <N_batch>
    csv_read: [wav]
    sentence_sorting: ascending
    replacements:
        $data_folder: !ref <data_folder>

test_loader: !new:speechbrain.DataLoaderFactory
    csv_file: !ref <csv_test>
    csv_read: [wav]
    sentence_sorting: ascending
    replacements:
        $data_folder: !ref <data_folder>

g_optimizer: !new:speechbrain.nnet.Optimizer
    OptClass: !name:torch.optim.Adam
    lr: !ref <lr>

d_optimizer: !new:speechbrain.nnet.Optimizer
    OptClass: !name:torch.optim.Adam
    lr: !ref <lr> / 4

modules:
    add_noise: !new:speechbrain.processing.AddNoise
    generator: !new:speechbrain.nnet.Sequential
        - [!ref <N_batch>, 100, 1]  # input_shape
        - !name:speechbrain.nnet.Conv1d
          out_channels: 32
          kernel_size: 11
        - !new:torch.nn.LeakyReLU
        - !name:speechbrain.nnet.Conv1d
          out_channels: 1
          kernel_size: 11
        - !new:torch.nn.Tanh
    discriminator: !new:speechbrain.nnet.Sequential
        - [!ref <N_batch>, 100, 1]  # input_shape
        - !name:speechbrain.nnet.Conv1d
          out_channels: 32
          kernel_size: 11
          stride: 8
        - !new:torch.nn.LeakyReLU
        - !name:speechbrain.nnet.Conv1d
          out_channels: 1
          kernel_size: 11
          stride: 8
        - !new:torch.nn.Sigmoid
    compute_cost: !name:speechbrain.nnet.mse_loss
