# ################################
# Model: VGG2 + LiGRU with time pooling for efficiency
# Additions: TimeDomainSpecAugment
# Authors: Mirco Ravanelli & Peter Plantinga 2020
# ################################

# Seed needs to be set at top of yaml, before objects with parameters are made
seed: 1234
__set_seed: !!python/object/apply:torch.manual_seed [!ref <seed>]
output_folder: !ref results/augment_noise_CRDNN/<seed>
wer_file: !ref <output_folder>/wer.txt
save_folder: !ref <output_folder>/save
train_log: !ref <output_folder>/train_log.txt

# Data files
data_folder: !PLACEHOLDER  # e.g. /path/to/TIMIT
csv_train: !ref <data_folder>/train.csv
csv_valid: !ref <data_folder>/dev.csv
csv_test: !ref <data_folder>/test.csv

# Training parameters
number_of_epochs: 50
batch_size: 8
lr: 1.0
device: 'cuda:0'

# Feature parameters
sample_rate: 16000
n_fft: 400
n_mels: 40

# Model parameters
activation: !name:torch.nn.LeakyReLU
dropout: 0.15
cnn_blocks: 2
cnn_channels: (128, 256)
cnn_kernelsize: (3, 3)
rnn_layers: 4
rnn_neurons: 512
rnn_bidirectional: True
dnn_blocks: 2
dnn_neurons: 512

# Outputs
output_neurons: 40
blank_index: !ref <output_neurons> - 1

train_loader: !new:speechbrain.DataLoaderFactory
    csv_file: !ref <csv_train>
    batch_size: !ref <batch_size>
    sentence_sorting: ascending
    output_folder: !ref <output_folder>
    csv_read: [wav, phn]

valid_loader: !new:speechbrain.DataLoaderFactory
    csv_file: !ref <csv_valid>
    batch_size: !ref <batch_size>
    sentence_sorting: ascending
    output_folder: !ref <output_folder>
    csv_read: [wav, phn]

test_loader: !new:speechbrain.DataLoaderFactory
    csv_file: !ref <csv_test>
    batch_size: !ref <batch_size>
    sentence_sorting: ascending
    output_folder: !ref <output_folder>
    csv_read: [wav, phn]

epoch_counter: !new:speechbrain.EpochCounter
    limit: !ref <number_of_epochs>

modules:
    epoch_counter: !ref <epoch_counter>
    wer_file: !ref <wer_file>
    augmentation: !new:speechbrain.lobes.TimeDomainSpecAugment
        sample_rate: !ref <sample_rate>
        speeds: [95, 100, 105]
    env_corrupt: !new:speechbrain.lobes.EnvCorrupt
        openrir_folder: !ref <data_folder>
        babble_prob: 0.0
        reverb_prob: 0.0
        noise_prob: 1.0
        noise_snr_low: 0
        noise_snr_high: 15
    compute_features: !new:speechbrain.lobes.Fbank
        sample_rate: !ref <sample_rate>
        n_fft: !ref <n_fft>
        n_mels: !ref <n_mels>
    model: !new:speechbrain.lobes.CRDNN
        input_shape: [!ref <batch_size>, 10, !ref <n_mels>]
        activation: !ref <activation>
        dropout: !ref <dropout>
        cnn_blocks: !ref <cnn_blocks>
        cnn_channels: !ref <cnn_channels>
        cnn_kernelsize: !ref <cnn_kernelsize>
        time_pooling: True
        rnn_layers: !ref <rnn_layers>
        rnn_neurons: !ref <rnn_neurons>
        rnn_bidirectional: !ref <rnn_bidirectional>
        dnn_blocks: !ref <dnn_blocks>
        dnn_neurons: !ref <dnn_neurons>
    output: !new:speechbrain.nnet.Linear
        input_size: !ref <dnn_neurons>
        n_neurons: !ref <output_neurons>
        bias: True
    log_softmax: !new:speechbrain.nnet.Softmax
        apply_log: True
    optimizer: !new:torch.optim.Adadelta
        params: !!python/object/apply:speechbrain.collect_params
            - !ref <modules.model>
            - !ref <modules.output>
        rho: 0.95
        lr: !ref <lr>
        eps: 1.e-8
    lr_annealing: !new:speechbrain.nnet.NewBobScheduler
        initial_value: !ref <lr>
        improvement_threshold: 0.0025
        annealing_factor: 0.8
        patient: 0
    normalize: !new:speechbrain.processing.InputNormalization
        norm_type: global
    compute_cost: !name:speechbrain.nnet.ctc_loss
        blank_index: !ref <blank_index>
    train_logger: !new:speechbrain.FileTrainLogger
        save_file: !ref <train_log>
    checkpointer: !new:speechbrain.utils.checkpoints.Checkpointer
        checkpoints_dir: !ref <save_folder>
        recoverables:
            model: !ref <modules.model>
            output: !ref <modules.output>
            optimizer: !ref <modules.optimizer>
            scheduler: !ref <modules.lr_annealing>
            normalizer: !ref <modules.normalize>
            counter: !ref <epoch_counter>
    ctc_stats: !name:speechbrain.MetricStats
        metric: !name:speechbrain.nnet.ctc_loss
            blank_index: !ref <blank_index>
            reduction: batch
    per_stats: !name:speechbrain.ErrorRateStats
