# ################################
# Model: VGG2 + LiGRU with time pooling for efficiency
# Author: Mirco Ravanelli 2020
# ################################

data_folder: !PLACEHOLDER  # e.g. /path/to/TIMIT
ckpts_to_keep: 1
sample_rate: 16000
seed: !PLACEHOLDER  # e.g, 1234
output_folder: !ref results/vgg_ligru/<seed>
predictions_file: !ref <output_folder>/predictions.csv
wer_file: !ref <output_folder>/wer.txt
save_folder: !ref <output_folder>/save
train_log: !ref <output_folder>/train_log.txt

# Data files
csv_train: !ref <data_folder>/train.csv
csv_valid: !ref <data_folder>/dev.csv
csv_test: !ref <data_folder>/test.csv

# Neural Parameters
number_of_epochs: 35
batch_size: 8
lr: 1.0
dropout_rate: 0.15
n_mels: 40

device: 'cuda:0'

# Functions
model: !speechbrain.lobes.models.CRDNN.CRDNN
    output_size: 40  # 39 phonemes + 1 blank symbol
    cnn_blocks: 2
    dnn_blocks: 2
    rnn_overrides: {rnn: {rnn_type: ligru}}
    time_pooling: True

optimizer: !speechbrain.nnet.optimizers.Optimize
    optimizer_type: adadelta
    rho: 0.95
    learning_rate: !ref <lr>

lr_annealing: !speechbrain.nnet.lr_scheduling.LRScheduler
    annealing_type: newbob
    N_epochs: !ref <number_of_epochs>
    lr_initial: !ref <lr>
    improvement_threshold: 0.0025
    annealing_factor: 0.8
    patient: 0

normalize: !speechbrain.processing.features.InputNormalization
    norm_type: global

compute_features: !speechbrain.lobes.features.fbank.Fbank

train_loader: !speechbrain.data_io.data_io.DataLoaderFactory
    &loader
    csv_file: !ref <csv_train>
    batch_size: !ref <batch_size>
    sentence_sorting: ascending
    output_folder: !ref <output_folder>
    csv_read: [wav, phn]

valid_loader: !speechbrain.data_io.data_io.DataLoaderFactory
    <<: *loader
    csv_file: !ref <csv_valid>

test_loader: !speechbrain.data_io.data_io.DataLoaderFactory
    <<: *loader
    csv_file: !ref <csv_test>
    batch_size: !ref <batch_size>

compute_cost: !speechbrain.nnet.losses.ComputeCost
    cost_type: [ctc]
    blank_index: 39
